- name: Create nagioscmd group
  group: name=nagioscmd state=present
  
- name: Add Nagios user and add it to nagioscmd group
  user: name=nagios groups=nagioscmd createhome=no append=yes
  
- name: Download nagios core
  get_url: url=http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-{{ nagios_version }}.tar.gz dest=/tmp/nagios-{{ nagios_version }}.tar.gz
  sudo: no 
- name: Untar the Nagios Core tarball
  unarchive: src=/tmp/nagios-{{ nagios_version }}.tar.gz dest=/tmp copy=no

- name: Download nagios plugins
  get_url: url=http://nagios-plugins.org/download/nagios-plugins-2.0.3.tar.gz dest=/tmp/nagios-plugins-2.0.3.tar.gz
  sudo: no
- name: Untar the Nagios Plugins Tarball
  unarchive: src=/tmp/nagios-plugins-2.0.3.tar.gz dest=/tmp copy=no

  
- name: Compile Nagios core (Configure script)
  command: "./configure --with-nagios-group=nagios --with-command-group=nagioscmd chdir=/tmp/nagios-{{ nagios_version }}"
  
- name: Compile Nagios core (Make)
  command: cd /tmp/nagios-{{ nagios_version }} && \

     make all && \
     make install && \
     make install-init && \
     make install-config && \
     make install-commandmode && \
     make install-webconfg

  
- name: Copy eventhandlers directory
  command: "cp -R contrib/eventhandlers/ /usr/local/nagios/libexec/ chdir=/tmp/nagios-{{ nagios_version }}"

  
- name: Set owner to nagios:nagioscmd
  file: path=/usr/local/nagios/libexec/ owner=nagios group=nagios recurse=yes
 
  
- name: Set password for nagiosadmin user
  htpasswd: path=/usr/local/nagios/etc/htpasswd.users name=nagiosadmin password=nagiosadmin owner=root group=www-data mode=0640
  notify:
  - restart apache
  
- name: Install needed packages --> nagios-nrpe-plugin
  yum: name={{ item }} state=present
  with_items:
    - nagios-nrpe-plugin
 
- name: Check if nagios plugins are already compiled
  command: /usr/local/nagios/libexec/check_nagios --version
  register: nagios_plugins_exists
  ignore_errors: True


  
- name: Compile Nagios Plugins (Configure script)
  command: "./configure --with-nagios-group=nagios --with-command-group=nagioscmd chdir=/tmp/nagios-plugins-2.0.3"

  
- name: Compile Nagios plugins (Make)
  command: "{{ item }} chdir=/tmp/nagios-plugins-2.0.3"
  with_items:
    - make
    - make install
 
  
- name: Enable rewrite Apache module
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - cgi
  notify:
    - restart apache
  
- name: Start nagios service
  service: name=nagios state=started

